### ISSUE TITLE
Feature Request: Refactoring UI

### ISSUE THREAD

**Issue by uniocto** [ramyashreeshetty/citibike-status-app#24]
Hi.
I came up with the following changes to improve your application usability.
- [ ] Remove buttons and render UI by selectbox change event
- [ ] Change selectbox option values from "id" to "Station name"
- [ ] Integrate two selectbox to one

If it becomes a direction to implement through the discussion here,
I would like to work on this.

Regards.

**Comment by ramyashreeshetty** [comment]
sure go ahead with this, actually i wanted to combine both the datasets and info together.
so u can look into it.
