### ISSUE TITLE
change the theme of the application

### ISSUE THREAD

**Issue by ramyashreeshetty** [ramyashreeshetty/citibike-status-app#4]
anything which looks attractive

**Comment by UjjwalMahar** [comment]
Hey I can Help with that please assign it to me.

**Comment by ramyashreeshetty** [comment]
sure

**Comment by UjjwalMahar** [comment]
Is it possible that we could connect in any other platform?
It would be easy to communicate regarding project.

Twitter - @UjjwalMahar

**Comment by ramyashreeshetty** [comment]
@UjjwalMahar ye we could connect on discord

**Comment by UjjwalMahar** [comment]
Discord please

**Comment by ramyashreeshetty** [comment]
Misaa#0148
