### ISSUE TITLE
add a logo

### ISSUE THREAD

**Issue by ramyashreeshetty** [ramyashreeshetty/citibike-status-app#5]
this application is based on citibike status in NY Region.
- Citi Bike is a privately owned public bicycle sharing system serving the New York City

Any logo suitable to this will work

**Comment by ujjwalban** [comment]
Assign this issue to me ,  I would like to contribute in it

**Comment by akshatjain1004** [comment]
I want to work on this, can you also please provide some description for the issue? @ramyashreeshetty

**Comment by ramyashreeshetty** [comment]
@akshatjain1004 i have updated it u can take a look

**Comment by akshatjain1004** [comment]
Got it! @ramyashreeshetty can you please assign it to me?

**Comment by akshatjain1004** [comment]
@ramyashreeshetty 
![image](https://user-images.githubusercontent.com/86458423/193574604-82e95eea-4d73-4df7-9764-146f2e3d619f.png)
I'm facing above issue when I'm trying to deploy my app on streamlit. Can you help me with it?

**Comment by ramyashreeshetty** [comment]
go to :  https://share.streamlit.io/
![image](https://user-images.githubusercontent.com/43513353/193575016-1f47c5fd-11ab-4377-8c7d-5ed036ed5ec0.png)


add secret key given in readme.md

**Comment by ramyashreeshetty** [comment]
@akshatjain1004 hey , are you still working on this issue?

**Comment by UjjwalMahar** [comment]
May I work on this issue if @akshatjain1004 is not currently working on it?

**Comment by akshatjain1004** [comment]
@ramyashreeshetty I'm sorry I'm not able to solve the issue

**Comment by ramyashreeshetty** [comment]
@akshatjain1004 no problem 👍🏽

**Comment by smiti-maheshwari** [comment]
Has anyone contributed to it @ramyashreeshetty? If not, can I try working on it?

**Comment by ramyashreeshetty** [comment]
@smiti-maheshwari actually someone is working on this currently, so I wont be able to assign this to u. You can look around for issues in the project. and create a new issue and then try to solve it

**Comment by smiti-maheshwari** [comment]
Thanks @ramyashreeshetty.
