### ISSUE TITLE
add citibike related images

### ISSUE THREAD

**Issue by ramyashreeshetty** [ramyashreeshetty/citibike-status-app#6]

**Comment by ph1ne4s** [comment]
can you assign this issue to me?

**Comment by ramyashreeshetty** [comment]
sure! please take care of size and format

**Comment by avijain09** [comment]
Please assign me this

**Comment by ramyashreeshetty** [comment]
@avijain09 i have already assigned it to someone else. You can check out other issues or create a new issue

**Comment by ramyashreeshetty** [comment]
@Aviral2002 hey are you working on this issue

**Comment by ph1ne4s** [comment]
@ramyashreeshetty yes, I will create a PR in few hours.

**Comment by ph1ne4s** [comment]
Actually, app is loading very slowly on streamlit.io

**Comment by ph1ne4s** [comment]
![Screenshot from 2022-10-04 22-13-28](https://user-images.githubusercontent.com/54772821/193878037-ca39691a-a92a-472c-92ff-54f3284597d9.png)

Displaying this since eternity😞
@ramyashreeshetty

**Comment by UjjwalMahar** [comment]
Check your network connection it might help

**Comment by ph1ne4s** [comment]
@UjjwalMahar internet connection is fine, checked multiple times.

**Comment by UjjwalMahar** [comment]
If it doesn't work try to reboot the application.

**Comment by ph1ne4s** [comment]
![Screenshot from 2022-10-05 13-25-50](https://user-images.githubusercontent.com/54772821/194009590-04057bb4-2a37-4e4b-823f-d4aaad0bab6d.png)

Stopped at this....

**Comment by ph1ne4s** [comment]
Ok.. It ran on my phone
@ramyashreeshetty could you merge my PR or suggest changes if required?

**Comment by ramyashreeshetty** [comment]
@Aviral2002 hey u need to add images related to citibike not citibank 😅 
anyways i'm closing this issue.
